[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test/unit"
evm_version = "cancun"
optimizer = true
optimizer-runs = 200
solc_version = "0.8.24"

[profile.holesky]
src = "src"
out = "out"
libs = ["lib"]
test = "test/holesky"
eth_rpc_url = "https://rpc.ankr.com/eth_holesky"
evm_version = "cancun"

[profile.mainnet]
src = "src"
out = "out"
libs = ["lib"]
test = "test/mainnet"
eth_rpc_url = "https://rpc.ankr.com/eth"
evm_version = "cancun"
