name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: nightly

      - name: Show Forge version
        run: |
          forge --version

      - name: Run Forge fmt default
        env:
          FOUNDRY_PROFILE: default
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge fmt fork tests
        env:
          FOUNDRY_PROFILE: mainnet
        run: |
          forge fmt --check
        id: fmt

      - name: Run Forge build
        run: |
          forge build --sizes
        id: build

      - name: Run Forge unit tests
        env:
          FOUNDRY_PROFILE: default
        run: |
          forge test -vvv
        id: test

      - name: Run Forge fork units
        env:
          FOUNDRY_PROFILE: mainnet
        run: |
          forge test -vvv
